ifdef ARCH
kernel: clean kernel-$(ARCH)
clean: clean-$(ARCH)
else
kernel:
	@echo "Target $(ARCH) is unsupported!"
clean: clean-x86_64 clean-i386
endif

clean-x86_64:

kernel-x86_64:

clean-i386:

kernel-i386:
	